import React from 'react'
import Card from './Card'

const Swiper = () => {
    
    return (
        <div id="swiper" className="swiper">
            <Card id="mydiv" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt nisi nisi. Vestibulum mattis diam sed mi rutrum, facilisis tincidunt lectus porta. Integer sagittis rutrum egestas. Morbi feugiat convallis felis, sed rhoncus nibh rutrum a. Mauris tristique leo sit amet lectus porttitor posuere. Aenean at leo vitae ante convallis pellentesque. Curabitur eu mollis velit. Suspendisse hendrerit vulputate augue, a dapibus urna volutpat vitae. Donec eget ipsum eu lacus sodales gravida. Phasellus elementum blandit tempor. Curabitur sodales non sem eget dignissim. Sed et maximus mi, et dapibus lacus. Donec a mattis nulla, eu fermentum ligula. Aliquam erat volutpat." />
            <Card id="mydiv" text="Donec vitae feugiat risus. Praesent vitae diam felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt mattis massa, eu scelerisque mi. Fusce condimentum viverra finibus. Duis ut urna mauris. Nam egestas lectus non dolor ultricies consequat." />
            <Card id="mydiv" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt nisi nisi. Vestibulum mattis diam sed mi rutrum, facilisis tincidunt lectus porta. Integer sagittis rutrum egestas. Morbi feugiat convallis felis, sed rhoncus nibh rutrum a. Mauris tristique leo sit amet lectus porttitor posuere. Aenean at leo vitae ante convallis pellentesque. Curabitur eu mollis velit. Suspendisse hendrerit vulputate augue, a dapibus urna volutpat vitae. Donec eget ipsum eu lacus sodales gravida. Phasellus elementum blandit tempor. Curabitur sodales non sem eget dignissim. Sed et maximus mi, et dapibus lacus. Donec a mattis nulla, eu fermentum ligula. Aliquam erat volutpat." />
            <Card id="mydiv" text="Donec vitae feugiat risus. Praesent vitae diam felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt mattis massa, eu scelerisque mi. Fusce condimentum viverra finibus. Duis ut urna mauris. Nam egestas lectus non dolor ultricies consequat." />
            <Card id="mydiv" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt nisi nisi. Vestibulum mattis diam sed mi rutrum, facilisis tincidunt lectus porta. Integer sagittis rutrum egestas. Morbi feugiat convallis felis, sed rhoncus nibh rutrum a. Mauris tristique leo sit amet lectus porttitor posuere. Aenean at leo vitae ante convallis pellentesque. Curabitur eu mollis velit. Suspendisse hendrerit vulputate augue, a dapibus urna volutpat vitae. Donec eget ipsum eu lacus sodales gravida. Phasellus elementum blandit tempor. Curabitur sodales non sem eget dignissim. Sed et maximus mi, et dapibus lacus. Donec a mattis nulla, eu fermentum ligula. Aliquam erat volutpat." />
            <Card id="mydiv" text="Donec vitae feugiat risus. Praesent vitae diam felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt mattis massa, eu scelerisque mi. Fusce condimentum viverra finibus. Duis ut urna mauris. Nam egestas lectus non dolor ultricies consequat." />
            <Card id="mydiv" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt nisi nisi. Vestibulum mattis diam sed mi rutrum, facilisis tincidunt lectus porta. Integer sagittis rutrum egestas. Morbi feugiat convallis felis, sed rhoncus nibh rutrum a. Mauris tristique leo sit amet lectus porttitor posuere. Aenean at leo vitae ante convallis pellentesque. Curabitur eu mollis velit. Suspendisse hendrerit vulputate augue, a dapibus urna volutpat vitae. Donec eget ipsum eu lacus sodales gravida. Phasellus elementum blandit tempor. Curabitur sodales non sem eget dignissim. Sed et maximus mi, et dapibus lacus. Donec a mattis nulla, eu fermentum ligula. Aliquam erat volutpat." />
            <Card id="mydiv" text="Donec vitae feugiat risus. Praesent vitae diam felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt mattis massa, eu scelerisque mi. Fusce condimentum viverra finibus. Duis ut urna mauris. Nam egestas lectus non dolor ultricies consequat." />
            <Card id="mydiv" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt nisi nisi. Vestibulum mattis diam sed mi rutrum, facilisis tincidunt lectus porta. Integer sagittis rutrum egestas. Morbi feugiat convallis felis, sed rhoncus nibh rutrum a. Mauris tristique leo sit amet lectus porttitor posuere. Aenean at leo vitae ante convallis pellentesque. Curabitur eu mollis velit. Suspendisse hendrerit vulputate augue, a dapibus urna volutpat vitae. Donec eget ipsum eu lacus sodales gravida. Phasellus elementum blandit tempor. Curabitur sodales non sem eget dignissim. Sed et maximus mi, et dapibus lacus. Donec a mattis nulla, eu fermentum ligula. Aliquam erat volutpat." />
            <Card id="mydiv" text="Donec vitae feugiat risus. Praesent vitae diam felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur tincidunt mattis massa, eu scelerisque mi. Fusce condimentum viverra finibus. Duis ut urna mauris. Nam egestas lectus non dolor ultricies consequat." />
            <Card id="mydiv" title='"Absence in design is very important"' />
        </div>
    )
}

export default Swiper
